title: "Leo Shaposhnik"
description: "Research in holography, quantum information, and emergent spacetime"

remote_theme: "mmistakes/minimal-mistakes"

url: "https://replicawormhole.github.io"
baseurl: "/homepage"
repository: "ReplicaWormhole/homepage"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-include-cache
