title: "Leo Shaposhnik"
description: "Research in holography, quantum information, and emergent spacetime"

remote_theme: "mmistakes/minimal-mistakes"

markdown: kramdown
kramdown:
  math_engine: mathjax
