title: "Leo Shaposhnik"
masthead_title: "LS"
description: "Research in holography, quantum information, and emergent spacetime"

remote_theme: "mmistakes/minimal-mistakes"

url: "https://replicawormhole.github.io"
baseurl: "/homepage"
repository: "ReplicaWormhole/homepage"

# This is the site code from GoatCounter's installation snippet.
# The tracking code respects a visitor's Do Not Track preference.
goatcounter_code: "leoshaposhnik"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-include-cache
